// mod print;
// mod vars;
// mod types;
// mod strings;
// mod tuples;
// mod arrays;
// mod vectors;
// mod conditionals;
// mod loops;
// mod functions;
// mod pointer_ref;
// mod structs;
//mod enums;
mod cli;

fn main() {
    // print::run();
    // println!("---- vars ----");
    // vars::run();
    // println!("---- types ----");
    // types::run();
    // println!("---- strings ----");
    // strings::run();
    // println!("---- tuples ----");
    // truples::run();
    // println!("---- arrays ----");
    // arrays::run();
    // println!("---- vectors ----");
    // vectors::run();
    // println!("---- conditionals ----");
    // conditionals::run();
    // println!("---- loops ----");
    // loops::run();
    // println!("---- functions ----");
    // functions::run();
    // println!("---- pointer_ref ----");
    // pointer_ref::run();
    // println!("---- structs ----");
    // structs::run();
    // println!("---- enums ----");
    // enums::run();
    println!("---- CLI ----");
    cli::run();
}
